// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usrmgn.proto

/*
Package usrmgn is a generated protocol buffer package.

It is generated from these files:
	usrmgn.proto

It has these top-level messages:
	LoginRequest
	QueryRequest
	ProfileRequest
	NicknameRequest
	UsrInfoReply
*/
package usrmgn

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type QueryRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ProfileRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Profile  string `protobuf:"bytes,2,opt,name=profile" json:"profile,omitempty"`
}

func (m *ProfileRequest) Reset()                    { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()               {}
func (*ProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProfileRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ProfileRequest) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

type NicknameRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
}

func (m *NicknameRequest) Reset()                    { *m = NicknameRequest{} }
func (m *NicknameRequest) String() string            { return proto.CompactTextString(m) }
func (*NicknameRequest) ProtoMessage()               {}
func (*NicknameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NicknameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *NicknameRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

type UsrInfoReply struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Nickname string `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Profile  string `protobuf:"bytes,3,opt,name=profile" json:"profile,omitempty"`
}

func (m *UsrInfoReply) Reset()                    { *m = UsrInfoReply{} }
func (m *UsrInfoReply) String() string            { return proto.CompactTextString(m) }
func (*UsrInfoReply) ProtoMessage()               {}
func (*UsrInfoReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UsrInfoReply) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UsrInfoReply) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UsrInfoReply) GetProfile() string {
	if m != nil {
		return m.Profile
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "usrmgn.LoginRequest")
	proto.RegisterType((*QueryRequest)(nil), "usrmgn.QueryRequest")
	proto.RegisterType((*ProfileRequest)(nil), "usrmgn.ProfileRequest")
	proto.RegisterType((*NicknameRequest)(nil), "usrmgn.NicknameRequest")
	proto.RegisterType((*UsrInfoReply)(nil), "usrmgn.UsrInfoReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Usrmgn service

type UsrmgnClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UsrInfoReply, error)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*UsrInfoReply, error)
	UploadProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*UsrInfoReply, error)
	ChangeNickname(ctx context.Context, in *NicknameRequest, opts ...grpc.CallOption) (*UsrInfoReply, error)
}

type usrmgnClient struct {
	cc *grpc.ClientConn
}

func NewUsrmgnClient(cc *grpc.ClientConn) UsrmgnClient {
	return &usrmgnClient{cc}
}

func (c *usrmgnClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*UsrInfoReply, error) {
	out := new(UsrInfoReply)
	err := grpc.Invoke(ctx, "/usrmgn.Usrmgn/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usrmgnClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*UsrInfoReply, error) {
	out := new(UsrInfoReply)
	err := grpc.Invoke(ctx, "/usrmgn.Usrmgn/Query", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usrmgnClient) UploadProfile(ctx context.Context, in *ProfileRequest, opts ...grpc.CallOption) (*UsrInfoReply, error) {
	out := new(UsrInfoReply)
	err := grpc.Invoke(ctx, "/usrmgn.Usrmgn/UploadProfile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usrmgnClient) ChangeNickname(ctx context.Context, in *NicknameRequest, opts ...grpc.CallOption) (*UsrInfoReply, error) {
	out := new(UsrInfoReply)
	err := grpc.Invoke(ctx, "/usrmgn.Usrmgn/ChangeNickname", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Usrmgn service

type UsrmgnServer interface {
	Login(context.Context, *LoginRequest) (*UsrInfoReply, error)
	Query(context.Context, *QueryRequest) (*UsrInfoReply, error)
	UploadProfile(context.Context, *ProfileRequest) (*UsrInfoReply, error)
	ChangeNickname(context.Context, *NicknameRequest) (*UsrInfoReply, error)
}

func RegisterUsrmgnServer(s *grpc.Server, srv UsrmgnServer) {
	s.RegisterService(&_Usrmgn_serviceDesc, srv)
}

func _Usrmgn_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrmgnServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usrmgn.Usrmgn/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrmgnServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usrmgn_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrmgnServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usrmgn.Usrmgn/Query",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrmgnServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usrmgn_UploadProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrmgnServer).UploadProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usrmgn.Usrmgn/UploadProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrmgnServer).UploadProfile(ctx, req.(*ProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usrmgn_ChangeNickname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NicknameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsrmgnServer).ChangeNickname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/usrmgn.Usrmgn/ChangeNickname",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsrmgnServer).ChangeNickname(ctx, req.(*NicknameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Usrmgn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "usrmgn.Usrmgn",
	HandlerType: (*UsrmgnServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Usrmgn_Login_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _Usrmgn_Query_Handler,
		},
		{
			MethodName: "UploadProfile",
			Handler:    _Usrmgn_UploadProfile_Handler,
		},
		{
			MethodName: "ChangeNickname",
			Handler:    _Usrmgn_ChangeNickname_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "usrmgn.proto",
}

func init() { proto.RegisterFile("usrmgn.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 260 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x2d, 0x2e, 0xca,
	0x4d, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0xdc, 0xb8, 0x78,
	0x7c, 0xf2, 0xd3, 0x33, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0x38,
	0x4a, 0x8b, 0x53, 0x8b, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0,
	0x7c, 0x90, 0x5c, 0x41, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x8a, 0x04, 0x13, 0x44, 0x0e, 0xc6,
	0x57, 0xd2, 0xe2, 0xe2, 0x09, 0x2c, 0x4d, 0x2d, 0xaa, 0x24, 0xc2, 0x1c, 0x25, 0x37, 0x2e, 0xbe,
	0x80, 0xa2, 0xfc, 0xb4, 0xcc, 0x9c, 0x54, 0x62, 0x6c, 0x95, 0xe0, 0x62, 0x2f, 0x80, 0xa8, 0x86,
	0x5a, 0x0a, 0xe3, 0x2a, 0x79, 0x72, 0xf1, 0xfb, 0x65, 0x26, 0x67, 0x83, 0x54, 0x11, 0xe9, 0xfc,
	0x3c, 0xa8, 0x72, 0x98, 0xf3, 0x61, 0x7c, 0xa5, 0x04, 0x2e, 0x9e, 0xd0, 0xe2, 0x22, 0xcf, 0xbc,
	0xb4, 0xfc, 0xa0, 0xd4, 0x82, 0x9c, 0x4a, 0x72, 0xcd, 0x41, 0x76, 0x2c, 0x33, 0x8a, 0x63, 0x8d,
	0x7e, 0x31, 0x72, 0xb1, 0x85, 0x82, 0xc3, 0x5c, 0xc8, 0x94, 0x8b, 0x15, 0x1c, 0xe6, 0x42, 0x22,
	0x7a, 0xd0, 0x38, 0x41, 0x8e, 0x02, 0x29, 0xb8, 0x28, 0xb2, 0x8b, 0x94, 0x18, 0x40, 0xda, 0xc0,
	0x41, 0x8c, 0xd0, 0x86, 0x1c, 0xe2, 0x38, 0xb5, 0xd9, 0x73, 0xf1, 0x86, 0x16, 0xe4, 0xe4, 0x27,
	0xa6, 0x40, 0xc3, 0x5c, 0x48, 0x0c, 0xa6, 0x10, 0x35, 0x12, 0x70, 0x1a, 0xe0, 0xc8, 0xc5, 0xe7,
	0x9c, 0x91, 0x98, 0x97, 0x9e, 0x0a, 0x0b, 0x6c, 0x21, 0x71, 0x98, 0x4a, 0xb4, 0xe0, 0xc7, 0x65,
	0x44, 0x12, 0x1b, 0x38, 0xd1, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x34, 0x33, 0x35, 0x5e,
	0x84, 0x02, 0x00, 0x00,
}
